name: NewsBot

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

jobs:
  newsbot:
    runs-on: ubuntu-latest
    environment: newsbot
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: DeterminateSystems/determinate-nix-action@v3.22.3
      - uses: denoland/setup-deno@v2.0.5
      - name: Setup environment
        run: |
          export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
          echo XDG_CONFIG_HOME="$XDG_CONFIG_HOME" >> $GITHUB_ENV

          export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
          echo XDG_DATA_HOME="$XDG_DATA_HOME" >> $GITHUB_ENV

          mkdir -v -p "$XDG_CONFIG_HOME/newsboat/"
          rsync -v -a ./newsboat/ "$XDG_CONFIG_HOME/newsboat/"
      - uses: actions/cache/restore@v6
        id: cache
        with:
          path: ${{ env.XDG_DATA_HOME }}/newsboat/
          key: newsboat-cache
      - name: Reload newsboat
        run: |
          nix run nixpkgs#newsboat -- -x reload
      - name: Send messages
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          deno run -A ./sendMessages.ts
      - name: Delete old cache
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh cache delete newsboat-cache || true
      - uses: actions/cache/save@v6
        with:
          path: ${{ env.XDG_DATA_HOME }}/newsboat/
          key: newsboat-cache
